name = "cf_ai_study_buddy"
main = "src/index.js"
compatibility_date = "2025-12-29"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "MEMORY"
class_name = "MemoryDO"

[[migrations]]
tag = "v1"
new_classes = ["MemoryDO"]

[workflows]
binding = "WORKFLOWS"
